#!/bin/bash

# =============================================================================
# Data preprocessing driver script
# Batch process nuScenes variants, convert questions, and run comparison analysis
# =============================================================================

# Exit on errors
set -e

# Colored logging helpers
print_info() {
    echo -e "\033[1;34m[INFO]\033[0m $1"
}

print_success() {
    echo -e "\033[1;32m[SUCCESS]\033[0m $1"
}

print_error() {
    echo -e "\033[1;31m[ERROR]\033[0m $1"
}

print_warning() {
    echo -e "\033[1;33m[WARNING]\033[0m $1"
}

# =============================================================================
# Configuration parameters
# =============================================================================

# First-timestamp variant data path generated by preprocess_variants_by_shard_first_moment.py and add_noise.py
ORIGINAL_DATA_PATH="${ORIGINAL_DATA_PATH:-data/nuscenes_dataset_first}"

# Project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Output directory configuration
OUTPUT_DIR_RELATIVE="nuscenes_variants_by_shard_impromptu_full"
SWITCH_OUTPUT_DIR_RELATIVE="nuscenes_switch"
COMPARISON_OUTPUT_FILE="comparison_results_final.xlsx"

# Data variant used for comparison
DATA_VARIANT="backlight"

# Maximum samples for testing
MAX_SAMPLES=""

# =============================================================================
# Script start
# =============================================================================

print_info "Start data preprocessing"
print_info "Project root: $PROJECT_ROOT"
print_info "First-timestamp variant data path: $ORIGINAL_DATA_PATH"
print_info "output directory: $OUTPUT_DIR_RELATIVE"
print_info "Converted output directory: $SWITCH_OUTPUT_DIR_RELATIVE"
print_info "Comparison result file: $COMPARISON_OUTPUT_FILE"

echo ""

# Check input data path
if [ ! -d "$ORIGINAL_DATA_PATH" ]; then
    print_error "First-timestamp variant data pathnot found: $ORIGINAL_DATA_PATH"
    print_error "Check the path or set ORIGINAL_DATA_PATH=/path/to/nuscenes_dataset_first"
    exit 1
fi

print_success "Input data path validated"

# toProject root
cd "$PROJECT_ROOT"
print_info "toProject root: $(pwd)"

# =============================================================================
# Step1: Run data preprocessing script
# =============================================================================

print_info "Step1: Run first-timestamp batch regeneration script"
print_info "Run: python preprocessing_scripts/batch_regenerate_first_moment_data.py"

# Build command
CMD1="python preprocessing_scripts/batch_regenerate_first_moment_data.py"
CMD1="$CMD1 --base_data_dir \"$ORIGINAL_DATA_PATH\""
CMD1="$CMD1 --output_dir \"$OUTPUT_DIR_RELATIVE\""

if [ -n "$MAX_SAMPLES" ]; then
    CMD1="$CMD1 --max_samples $MAX_SAMPLES"
fi

print_info "Command: $CMD1"

# Runfirst script
if eval $CMD1; then
    print_success "Step1Done: data preprocessing succeeded"
else
    print_error "Step1failed: data preprocessing failed"
    exit 1
fi

echo ""

# =============================================================================
# Step2: Run question conversion script
# =============================================================================

print_info "Step2: Run question conversion script"
print_info "Run: python preprocessing_scripts/question_switch/utils_switch/main_converter.py"

# Build command
CMD2="python preprocessing_scripts/question_switch/utils_switch/main_converter.py"
CMD2="$CMD2 --input_path \"$OUTPUT_DIR_RELATIVE\""
CMD2="$CMD2 --output_path \"$SWITCH_OUTPUT_DIR_RELATIVE\""
CMD2="$CMD2 --overwrite"

print_info "Command: $CMD2"

# Run
if eval $CMD2; then
    print_success "Step2Done: question conversion succeeded"
else
    print_error "Step2failed: question conversion failed"
    exit 1
fi

echo ""

# =============================================================================
# Step3: Run comparison analysis script
# =============================================================================

print_info "Step3: Run comparison analysis script"
print_info "Run: python preprocessing_scripts/question_switch/compare_final.py"

# Build command
CMD3="python preprocessing_scripts/question_switch/compare_final.py"
CMD3="$CMD3 --original_dir \"$OUTPUT_DIR_RELATIVE\""
CMD3="$CMD3 --converted_dir \"$SWITCH_OUTPUT_DIR_RELATIVE\""
CMD3="$CMD3 --output_file \"$COMPARISON_OUTPUT_FILE\""
CMD3="$CMD3 --data_variant \"$DATA_VARIANT\""

print_info "Command: $CMD3"

# Run
if eval $CMD3; then
    print_success "Step3Done: comparison analysis succeeded"
else
    print_error "Step3failed: comparison analysis failed"
    exit 1
fi

echo ""

# =============================================================================
# Step4: Remove q7 entries
# =============================================================================

print_info "Step4: Remove q7 entries from JSON files under nuscenes_switch"
print_info "Run: python preprocessing_scripts/question_switch/remove_q7_content.py"

# Build command
CMD4="python preprocessing_scripts/question_switch/remove_q7_content.py"

print_info "Command: $CMD4"

# Run
if eval $CMD4; then
    print_success "Step4Done: q7 removal succeeded"
else
    print_error "Step4failed: q7 removal failed"
    exit 1
fi

echo ""

# =============================================================================
# Summary
# =============================================================================

print_success "ProcessingStepDone！"
print_info "Results:"
print_info "  - Preprocessed data directory: $OUTPUT_DIR_RELATIVE"
print_info "  - Converted data directory: $SWITCH_OUTPUT_DIR_RELATIVE"
print_info "  - Comparison result: $COMPARISON_OUTPUT_FILE"
print_info "  - q7 entries removed from converted data"

print_info "Next steps:"
print_info "  1. Check generated data files"
print_info "  2. Comparison result"
print_info "  3. Run inference scripts for model evaluation"

print_success "Data preprocessing completed！"
